project_id          = "teamwork-terraform"
credentials_path    = "function/gcpcredentials.json"
username            = "twp_mRjw8qakwusKQNX4svPO5XjGH8Tj_eu"
password            = "."
dataset_name        = "teamwork_data"
table_name          = "tasks"
teamwork_project_id = "318649"